### PR TITLE
Remove FedRAMP Catalog and Baseline Profiles

### PR DESCRIPTION
**Pull request by ohsh6o**
# Committer Notes

Per GSA/fedramp-automation#89 and previous discussion, this PR will remove the oscal-content copy of the FedRAMP catalog and baseline profiles.

### All Submissions:

- [X] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/oscal-content/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/oscal-content/pulls) for the same update/change?
- [X] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?

### CODE REVIEW

**Review by david-waltermire-nist — CHANGES_REQUESTED** [review]
This is really great. One small thing... can you add README.md files to each content directory that point to the corresponding folder in the fedramp-automation repo?

**Comment by iMichaela** [comment]
In case you need it, here is an example of [README.md](https://github.com/usnistgov/OSCAL/blob/main/content/nist.gov/SP800-53/README.md)

**Comment by ohsh6o** [comment]
> In case you need it, here is an example of [README.md](https://github.com/usnistgov/OSCAL/blob/main/content/nist.gov/SP800-53/README.md)

Changes will be coming shortly!

**Comment by ohsh6o** [comment]
@david-waltermire-nist and @iMichaela: updates complete. Let me know if it is good for merge after your next review. Thanks in advance for your feedback thus far.

**Review by oscalbuilder — APPROVED** [review]
This looks good to me. Thanks!

**Review by david-waltermire-nist — APPROVED** [review]
LGTM!

**Pull request merged**
