### PR TITLE
NIST SP800-53 catalog with labels restored

### LINKED ISSUE #72: Erroneous self-reference on SC-12
# Describe the bug

In _NIST_SP-800-53_rev5_catalog.json_ there is a self-reference from control SC-12 to SC-12 (itself).

# Who is the bug affecting?

Everyone working with the example catalog.

# What is affected by this bug?

Data consistency.

# When does this occur?

When importing the data into a tool.

# How do we replicate the issue?

Please see the attached screenshots:

* I highlighted the link in the JSON file.
* I noticed the self-reference while importing this data into the Neo4J graph database. It's immediately obvious in the graph:

Bildschirmfoto von 2021-05-10 09-07-11

Bildschirmfoto von 2021-05-10 09-02-57

# Expected behavior (i.e. solution)

This reference should not be present.

# Other Comments

I noticed this while importing the OSCAL content into a Neo4J database. The scripts I am using are available in my [Github repo](https://github.com/Agh42/comply-22/tree/main/data/NIST-800-53/script)

### LINKED ISSUE #237: OSCAL NIST SP 800-53 rev 5.1.1 catalog with earlier version of the "prop/@name=label" system restored.
### User Story

As an user of the OSCAL NIST SP 800-53 rev 5.1.1 catalog, I would like to have the a catalog version with a label system similar to previous versions.

### Goals

All controls will have the prop/@name="label" restored.

### Dependencies

none

### Acceptance Criteria

- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### PR DESCRIPTION
**Pull request by iMichaela**
# Committer Notes

The PR fixes #237 by restoring the `prop/@name="label"` for backwards compatibility with previous oscal versions of the catalog. Additionally, the PR fixes #72  by removing the self-reference error in SC-12 to align with the corrected CPRT data.

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/oscal-content/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/oscal-content/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Comment by iMichaela** [comment]
In the latest OSCAL version of the NIST SP 800-53 (v5.1.1+u4), each catalog has:
1)
```
<prop name="label" class="zero-padded" value="AC-02"/>
```
This was done to align with he CPRT data and promote zero-padded control IDs until v6 when we will be able to break the backwards compatibility and add those zero-padded IDs as OSCAL control IDs as well.

NOTE: This decision was made in collaboration with the community members and per @david-waltermire note that RMF team's lead is not prescriptive with respect the the accuracy of the zero-padded control IDs' representation as OSCAL IDs or as alternative identifiers. The dialog and community's input is available [on OSCAL/Lobby](https://matrix.to/#/!KiqEhMrfjXqEyIwUMw:gitter.im/$Du_QCs8GIpMrwSKPKvtReCwXHczPMBryL1LNNmCVtqg?via=gitter.im&via=matrix.org&via=matrix.freyachat.eu)

2)
```
      <prop name="label" value="AC-2"/>
```
This was done to support the backwards compatibility for tools relying on the such labels fro generating human-friendly versions of the catalog.

**Comment by iMichaela** [comment]
The PR is ready for community's review, in addition to NIST team's review.

**Review by david-waltermire — APPROVED** [review]
This PR restores the non-zero-padded control labels, removing the alt-identifier properties. I reviewed a diff of the catalog and it looks good. Thank you.

**Review by wendellpiez — APPROVED** [review]
LGTM thank you

**Comment by iMichaela** [comment]
[CALL TO ACTION]: The [OSCAL content PR #238](https://github.com/usnistgov/oscal-content/pull/238) updating the NIST SP 800-53 v5.1.1 is proposing restoring of the `prop/@name="label"` with no zero-leading control IDs and it is adding ` prop/@name="label"` with zero-leading control IDs. NIST team greatly appreciates community members review and approval to ensure broad acceptance of the NIST SP 800-53 v3.1.1 catalog in OSCAL.

**The PR will be merged at the end of the month if no comments/objections are received.**

**Pull request merged**
