### PR TITLE
Add Content Generation for Develop Branch

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

This will close usnistgov/oscal-content#132. I wanted to ensure we share resolved profiles and other content following review and merge of work for usnistgov/oscal-content#97 and lower burden for our own devs and outside contributors to see the result.

Also related notionally to dev feedback in usnistgov/oscal-content#120 .

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/oscal-content/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/oscal-content/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you included examples of how to use your new feature(s)?~

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
During weekly status review, I agreed to add some more debugging steps to collect state in the workspace for debugging in the event the build breaks or fails. Will do that ASAP for Dave to quickly review today.

**Comment by aj-stein-nist** [comment]
> During weekly status review, I agreed to add some more debugging steps to collect state in the workspace for debugging in the event the build breaks or fails. Will do that ASAP for Dave to quickly review today.


Note to AJ for posterity: going to splice content in from https://github.com/aj-stein-nist/oscal-content/commit/b5b1bd96826511f0fc751cb9df7a86aee952ab5b into the `content-artifacts.yaml` workflow.

**Comment by aj-stein-nist** [comment]
Alright @david-waltermire-nist, code added and ready for prompt review. Below is a sample workflow run (_it failed, but that is good for this reason_) to show the debugging content collected and attached to the run. This shows `always()` working with sad path, not just happy path.

https://github.com/usnistgov/oscal-content/actions/runs/3024676041

**Review by david-waltermire-nist — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
