### PR TITLE
Test usnistgov/OSCAL#1703 for upcoming release.

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

Test usnistgov/OSCAL#1703 for upcoming release.

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/oscal-content/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/oscal-content/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you included examples of how to use your new feature(s)?~

### CODE REVIEW

**Comment by JustKuzya** [comment]
I would need to understand the way Metaschema works to provide a correct or approximating a correct review. The outer commit claims that only one file had changed, while inside the commit changed 91 files. I get that there are some CI/CD generated files, but I'd like to hear from you, AJ.

**Comment by aj-stein-nist** [comment]
> I would need to understand the way Metaschema works to provide a correct or approximating a correct review. The outer commit claims that only one file had changed, while inside the commit changed 91 files. I get that there are some CI/CD generated files, but I'd like to hear from you, AJ.

Oh I staged the PR as draft but this is likely not ready yet, we definitely need to have a conversation on the questions you asked. That is important and is coming! :-)

**Comment by aj-stein-nist** [comment]
@JustKuzya for this build we do not need to merge things into a separate testing PR unless we find that suitable (this time or a next time). In this case you or I can download the artifacts ZIP archive [off of the successfuly workflow run here](https://github.com/usnistgov/oscal-content/suites/12028811364/artifacts/632142352) and review that. That is what I am doing, or by locally testing the branch and looking at `git diff` on commits.

**Comment by aj-stein-nist** [comment]
This is looking good so far now that I have done a review with this and #189 to spot check. Will review with the team and get more formal reviews tomorrow.

**Pull request closed without merging**
