### PR TITLE
Add Examples of OSCAL Actions Assembly

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

This PR closes usnistgov/oscal-content#130.

Depends on usnistgov/metaschema#240 and usnistgov/metaschema#241

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/oscal-content/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/oscal-content/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you included examples of how to use your new feature(s)?
- ~Have you written new tests for your core changes, as applicable?~

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist, sorry, I cannot change it to draft back bc of perms/I am the author the PR. This is WIP until otherwise stated, can you help me change it back? :-)

**Comment by aj-stein-nist** [comment]
OK, so I talked with Wendell through a potential bug in the supermodel -> converter generator -> running the OSCAL XML to JSON converter on some example files in here, specifically [`oscal_leveraging-example_ssp.xml`](https://github.com/aj-stein-nist/oscal-content/blob/b5b1bd96826511f0fc751cb9df7a86aee952ab5b/src/examples/ssp/xml/oscal_leveraging-example_ssp.xml#L22). This is causing this error with examples file in the updated pipelines in this branch using more current `develop` OSCAL and in it `develop` metaschema submodule updates.

```xml
<nm:ERROR xmlns:err="http://www.w3.org/2005/xqt-errors" xmlns:nm="http://csrc.nist.gov/ns/metaschema" code="err:FOJS0006">xml-to-json: Child elements of &lt;map&gt; must have a key attribute</nm:ERROR>
```

It would seem this has something to do with how specifically this `system-id ` without a `type` URI is handled with the current supermodel analysis in making the converters with the converter generator. I am having trouble piecing together where the model analysis occurs in the pipeline and the super model itself is generated, but I finally noticed the key difference I was not noticing on Friday.

The `system-id` in the generated supermodel:

```xml
      <group in-json="ARRAY" key="system-ids">
         <field collapsible="no" as-type="string" name="system-id" gi="system-id"><!-- NOTE: the field should have an in-json="SCALAR" attribute or something sensible, but it does not. -->
            <value as-type="string" key="id" in-json="string">saas_system_iaas_customer</value>
         </field>
      </group>
```

I will potentially convert this into a metaschema bug report when I am sure it is a bug and know more when discussing with Wendell on Monday or early next week.

Some other examples in the example document instance converted to the supermodel I hadn't noticed before.

```xml
                     <group in-json="ARRAY" key="information-type-ids">
                        <field collapsible="no" as-type="string" name="information-type-id"
                           gi="information-type-id" in-json="SCALAR">
                           <value as-type="string" in-json="string">C.3.5.8</value>
                        </field>
                     </group>
```

```xml
            <group in-json="ARRAY" key="role-ids">
               <field collapsible="no" as-type="token" name="role-id" gi="role-id" in-json="SCALAR">
                  <value as-type="token" in-json="string">admin</value>
               </field>
            </group>
```

```xml
                  <group in-json="ARRAY" key="functions-performed">
                     <field collapsible="no" as-type="string" name="function-performed"
                        gi="function-performed" in-json="SCALAR">
                        <value as-type="string" in-json="string">Manages the components within the
                           SaaS.</value>
                     </field>
                  </group>
```


```xml
                  <group in-json="ARRAY" key="values">
                     <field collapsible="no" as-type="string" name="parameter-value" gi="value"
                        in-json="SCALAR">
                        <value as-type="string" in-json="string">privileged and
                           non-privileged</value>
                     </field>
                  </group>
```

**Comment by aj-stein-nist** [comment]
To move this along for now: I rebased this off of the current PR in usnistgov/oscal-content#116. Since that is a branch off my fork, I cannot really point that as the target of this PR. If the CI/CD fixes land, I can rebase again, examples will validate, and builds will work when this work is reviewed and merged as well.

**Comment by aj-stein-nist** [comment]
This still needs rebasing after usnistgov/metaschema#240 and usnistgov/metaschema#241 are merged into usnistgov/OSCAL and the submodule can be updated to touch up CI/CD issues, but the example content is in a good place for the NIST team and OSCAL community to review the examples content on its merits separate of those issues.

**Review by david-waltermire-nist — CHANGES_REQUESTED** [review]
The content is fairly straight forward, so no concerns there.

I'd like to see you adjust the readme to have a single readme in the ssp folder that points to the xml, json, and yaml variants.

**Comment by aj-stein-nist** [comment]
Talked with Dave during a sync and I have to work out the following items:
- [ ] relocate the README me to [`./src/examples/ssp`] and not its `xml` subdirectory so it is handled across the different data-format sub-dirs post generation
- [ ] do wait and fix the CI before merge of this
- [ ] do not merge or push up remotely adapted [`./src.config`] file

**Comment by david-waltermire-nist** [comment]
@aj-stein-nist As we discussed today, this needs to be rebased to address the CI problems. Let me know when this is done and I can merge this PR.

**Comment by aj-stein-nist** [comment]
This is blocked by https://github.com/usnistgov/oscal-content/pull/183 and any pending work that must be resolved and completed as marked by the resolution of https://github.com/usnistgov/oscal-content/issues/116.

**Pull request closed without merging**
