### PR TITLE
Updates for SP800-53 plus baselines with corrections to errata (Dec 10)

### PR DESCRIPTION
**Pull request by wendellpiez**
# Committer Notes

This commit addresses #48 as well as #43.

Changes to the catalog reflect corrections made in the base text, addressing errata.

The baselines (profiles) are the same, except for the removal of one control enhancement from the `PRIVACY` baseline.

Schematrons for validating the SP800-53 catalogs and profiles are also included for the convenience of consumers.

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/oscal-content/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/oscal-content/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them? *n/a*
- [x] Have you written new tests for your core changes, as applicable? *n/a*
- [x] Have you included examples of how to use your new feature(s)? *n/a*

### CODE REVIEW

**Comment by wendellpiez** [comment]
@iMichaela please take a look. We actually caught a substantial lapse in extraction of contents for SI-4 - a list was being mangled.  (Where source data uses literal numbering not an encoded style and my filter that was meant to detect and repair, was failing.) It looks okay now.

**Comment by iMichaela** [comment]
@wendellpiez I will review the PR on Monday. Can you assign the review to me, please. Also, the OSCAL content (privacy baseline) validation process completes, but exits with error code 1, and no other details.

**Comment by wendellpiez** [comment]
@david-waltermire-nist could you look and see why this is failing the build?

@iMichaela I think all the data is good now, or at least please let me know what you find.

**Review by iMichaela — CHANGES_REQUESTED** [review]
@wendellpiez  - The baselines are listing OSCAL version M3 while your commit #3 indicates that the RC1 version was used. The catalog uses RC1 schema. Please update the baselines to RC1 as well.

**Review by iMichaela — APPROVED** [review]

**Review by iMichaela — APPROVED** [review]

**Review by iMichaela — APPROVED** [review]

**Review by iMichaela — APPROVED** [review]

**Review by iMichaela — APPROVED** [review]

**Review by iMichaela — APPROVED** [review]

**Review by iMichaela — DISMISSED** [review]

**Comment by wendellpiez** [comment]
When this is up I need to refresh data with the FISMA team is there some way to trigger that?

**Review by david-waltermire-nist — APPROVED** [review]
LGTM!

**Pull request merged**
