### PR TITLE
Added label properties to groups

### PR DESCRIPTION
**Pull request by brian-comply0**
# Committer Notes

Added label properties to groups in NIST SP 800-53 r4 and r5, so that tools that honor the label property will have data to use.

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/oscal-content/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/oscal-content/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?

### CODE REVIEW

**Comment by iMichaela** [comment]
@brian-comply0 - Thank you for following your opened issue https://github.com/usnistgov/oscal-content/issues/268 so fast with this PR that is addressing it. It is something we, at NIST, dreamed for a long time: that the community provide solutions in addition to the issue created.
With that said:
1) We do not push anything directly to main. The PR will have to be submitted against the develop branch and be part of a patch release. 
2) Before we get there, we need to make sure the issue https://github.com/usnistgov/oscal-content/issues/268 is endorsed by others in the community as well and the feature you proposed (group label props) is needed by all community members or, at minimum, is not causing more work for them to update the parsers.

**Comment by brian-comply0** [comment]
@iMichaela thank you for clarifying the target branch. I've updated it. 

I fully respect the need to at least ensure this will not cause disruption and ideally hear if there is other interest.

**Comment by iMichaela** [comment]
> @iMichaela thank you for clarifying the target branch. I've updated it.
> 
> I fully respect the need to at least ensure this will not cause disruption and ideally hear if there is other interest.

Thank you @brian-comply0 .  Let's give the community a little time to provide their perspective. Current week might not be the best to engage the community.

**Comment by brian-comply0** [comment]
Per discussion with @iMichaela I am splitting this PR into two separate PRs, so that the Rev 4 and Rev 5 changes may be adjudicated independently. 
Rev 5 is now in PR #271 
Rev 4 is now in PR #272 

Closing this PR unmerged.

**Pull request closed without merging**
