### PR TITLE
Remove invalid profiles with incorrect imports for certain Rev5 profiles

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

This is 1/2 approaches to close usnistgov/oscal-content#168. We can do either of the following, based on this PR's feedback.

1. ~Change the errant `/profile/import/@href`s as needed to pass validation (as currently written in the PR).~
1. Update the PR to just delete all draft profiles as the requirements/needs/values for their continued existence in the repo is unclear.

After review and subsequent discussion, Option 2 was selected.

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/oscal-content/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/oscal-content/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you included examples of how to use your new feature(s)?~

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
The failed run of the GHA workflow is because we need https://github.com/usnistgov/OSCAL/pull/1598 to be merged and then a submodule update targeting the `develop` branch of this repo. Parking this for now.

**Comment by david-waltermire-nist** [comment]
@aj-stein-nist We discussed deleting the old draft SP 800-53 rev5 files today during the NIST team meeting. There were no concerns raised. Please remove the draft version in both the [src](https://github.com/usnistgov/oscal-content/tree/main/src/nist.gov/SP800-53/rev5/xml/draft) and [built artifact](https://github.com/usnistgov/oscal-content/tree/main/nist.gov/SP800-53/rev5) directories. This will address this issue.

**Comment by aj-stein-nist** [comment]
We have to slide up `develop` for CI and then CD to work for that silly maven.restlet.org workaround. I am pretty certain, this is a reminder for me to get back to that.

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist and @wendellpiez, can I please have this reviewed so I can potentially merge? This #157 will both fail and each is the cause of the other as a result of two build failures. I would like to clear them at the same time and then touch up other fixes to develop in a sequence. Thanks!

**Review by wendellpiez — APPROVED** [review]
This is excellent: thank you.

**Pull request merged**
