### PR TITLE
Upgrade GitHub CI/CD Workflows to Current Stable Version

### PR DESCRIPTION
**Pull request by aj-stein-nist**
# Committer Notes

Closes usnistgov/oscal-content#116.

For testing, I pushed to `main` on my developer fork and ran GitHub Actions as if this was merged here as well:

https://github.com/aj-stein-nist/oscal-content/actions/runs/3139302623

https://github.com/aj-stein-nist/oscal-content/commit/e0b05be86133f2845e24f3723a22841e990de96f

This is ready for review, but several things must be completed before this is valid and mergeable:
- [x] https://github.com/usnistgov/OSCAL/pull/1518 must be merged into OSCAL develop
- [x] current dependency PRs in [this active list as of today](https://github.com/usnistgov/OSCAL/pulls?q=is%3Apr+is%3Aopen+label%3Agithub_actions+label%3Adependencies) must be merged into OSCAL develop after 
this
- [ ] This repo must have a PR created to take updated OSCAL develop branch and refresh that as a submodule in the oscal-content develop branch
- [ ] This repo must have a PR created to take updated OSCAL main branch and refresh that as a submodule in the oscal-content main branch

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/oscal-content/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/oscal-content/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- ~Have you added an explanation of what your changes do and why you'd like us to include them?~
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you included examples of how to use your new feature(s)?~

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist this one is GTG. I did leave 3 separate commits for us to discuss/review prior to merge, the second for Dependabot, and most importantly and last, pulling up the submodule to make this possible using pinned deps from files. I presume the latter may or may not be desirable given release priorities and strategy here let me know.

Marking this one ready for review and feedback.

**Comment by aj-stein-nist** [comment]
After touchups in the upstream develop branch of usnistgov/OSCAL, I should come back to this quickly with a second pass later in the week and align the version numbers to cut down on GHA Dependabot churn here once it is merged immediately after.

**Comment by david-waltermire-nist** [comment]
@aj-stein-nist Is this ready to review and merge?

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist Is this ready to review and merge?

It might be best if I update some of the GitHub Actions versions now that we merged a ton of them upstream in OSCAL repo as well. Give me a few minutes. I will spruce up here and ping you when it is ready.

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist dependencies updated and this is ready for re-review. I would argue we might want to hold off on merge and discuss implications of this comment first: https://github.com/usnistgov/oscal-content/pull/144#issuecomment-1260103082. Just reviewed previous work to make sure I didn't miss anything.

**Review by david-waltermire-nist — APPROVED** [review]
Thanks!

**Pull request merged**
